### PR TITLE
Swift 4.2 migration

### PR DESCRIPTION
**Pull request by baidikoff**

### CODE REVIEW

**Comment by tpoche** [comment]
Please merge ASAP as this issue is preventing our team from using this package currently!  Otherwise, we will have to start using another fork.

**Comment by GentaObata** [comment]
please merge! using me too!!

**Comment by ykyouhei** [comment]
@baidikoff @tpoche @GentaObata 
very sorry :confounded:
merged!! 👍

**Comment by GentaObata** [comment]
thanks!

**Comment by tpoche** [comment]
Thank you very much!  Cheers!

**Pull request merged**
